using System.Diagnostics.CodeAnalysis;

namespace BusproService.Enums
{
	//Protocol for Relay V1.0.0
	//Protocol for Dimmer V1.0.0
	//Protocol for 9in1 V1.0.0 t.o.m. kapittel 1.16

	[SuppressMessage("ReSharper", "InconsistentNaming")]
	public enum OperationCode
	{
		NotSet = 0x0,

		SingleChannelControl = 0x0031,
		SingleChannelControlResponse = 0x0032,
		ReadStatusOfChannels = 0x0033,
		ReadStatusOfChannelsResponse = 0x0034,
		CurtainControlEnabled = 0xDC23,
		CurtainControlEnabledResponse = 0xDC24,
		DetectAddress = 0xE5F5,
		DetectAddressResponse = 0xE5F6,
		BroadcastStatusOfScene = 0xEFFF,
		IsAddressConflict = 0x0284,
		IsAddressConflictResponse = 0x0285,
		IsDeviceOnline = 0xF065,
		IsDeviceOnlineResponse = 0xF066,
		MakeZones = 0x0006,
		MakeZonesResponse = 0x0007,
		ModifyAddress = 0xE5F7,
		ModifyAddressResponse = 0xE5F8,
		ModifyChannelLoadType = 0xF014,
		ModifyChannelLoadTypeResponse = 0xF015,
		ModifyDelayOfTurnOnChannel = 0xF04F,
		ModifyDelayOfTurnOnChannelResponse = 0xF050,
		ModifyDetailOfASequenceInSpecifiedZone = 0x0016,
		ModifyDetailOfASequenceInSpecifiedZoneResponse = 0x0017,
		ModifyLock = 0x0282,
		ModifyLockResponse = 0x0283,
		ModifyMacAddress = 0xF001,
		ModifyMacAddressResult = 0xF002,
		ModifyRemarkOfSpecifiedSequence = 0xF030,
		ModifyRemarkOfSpecifiedSequenceResponse = 0xF031,
		ModifySafeguardTimeOfChannel = 0xF041,
		ModifySafeguardTimeOfChannelResponse = 0xF042,
		ModifySceneConfiguration = 0x0008,
		ModifySceneConfigurationResponse = 0x0009,
		ModifySceneNoOfEveryZoneWhenPowerOn = 0xF057,
		ModifySceneNoOfEveryZoneWhenPowerOnResponse = 0xF058,
		ModifySettingOfSequenceRunning = 0x0018,
		ModifySettingOfSequenceRunningResponse = 0x0019,
		ModifySubnetIdAndDeviceIdByMacAddress = 0xF005,
		ModifySubnetIdAndDeviceIdByMacAddressResponse = 0xF006, //0xF002 i dokumentasjon, dette er nok feil
		ReadChannelLoadType = 0xF012,
		ReadChannelLoadTypeResponse = 0xF013,
		ReadChannelRemark = 0xF00E,
		ReadChannelRemarkResponse = 0xF00F,
		ReadDelayOfTurnOnChannel = 0xF04D,
		ReadDelayOfTurnOnChannelResponse = 0xF04E,
		ReadDetailOfASequenceInSpecifiedZone = 0x0014,
		ReadDetailOfASequenceInSpecifiedZoneResponse = 0x0015,
		ReadDeviceRemark = 0x000E,
		ReadDeviceRemarkResponse = 0x000F,
		ReadFirmwareVersion = 0xEEFD,
		ReadFirmwareVersionResponse = 0xEEFE,
		ReadLimitOfEveryChannel = 0xF016,
		ReadLimitOfEveryChannelResponse = 0xF017,
		ReadLock = 0x0280,
		ReadLockResponse = 0x0281,
		ReadMacAddress = 0xF003,
		ReadMacAddressResult = 0xF004,
		ReadRemarkOfOneZone = 0xF00A,
		ReadRemarkOfOneZoneResponse = 0xF00B,
		ReadRemarkOfSpecifiedSceneOfSpecifiedZone = 0xF024,
		ReadRemarkOfSpecifiedSceneOfSpecifiedZoneResponse = 0xF025,
		ReadRemarkOfSpecifiedSequence = 0xF028,
		ReadRemarkOfSpecifiedSequenceResponse = 0xF029,
		ReadSafeguardTimeOfChannel = 0xF03F,
		ReadSafeguardTimeOfChannelResponse = 0xF040,
		ReadSceneConfiguration = 0x0000,
		ReadSceneConfigurationResponse = 0x0001,
		ReadSceneNoOfAllZonesRunning = 0xF078,
		ReadSceneNoOfAllZonesRunningResponse = 0xF079,
		ReadSceneNoOfEveryZoneWhenPowerOn = 0xF055,
		ReadSceneNoOfEveryZoneWhenPowerOnResponse = 0xF056,
		ReadSequenceNoOfSpecifiedZoneRunning = 0xE014,
		ReadSequenceNoOfSpecifiedZoneRunningResponse = 0xE015,
		ReadSettingOfSequenceRunning = 0x0012,
		ReadSettingOfSequenceRunningResponse = 0x0013,
		ReadSettingsOfZones = 0x0004,
		ReadSettingsOfZonesResponse = 0x0005,
		ReadTypeOfZoneWhenPowerOn = 0xF051,
		ReadTypeOfZoneWhenPowerOnResponse = 0xF052,
		RequestCurrentSmallPackageFromPcToTargetDevice = 0xDC14,
		RequestCurrentSmallPackageFromPcToTargetDeviceResponse = 0xDC15,
		RequestTotalQtyOfPackagesFromPcToTargetDevice = 0xDC10,
		RequestTotalQtyOfPackagesFromPcToTargetDeviceResponse = 0xDC11,
		ReversingControl = 0xDC1C,
		ReversingControlResponse = 0xDC1D,
		SceneControl = 0x0002,
		SceneControlResponse = 0x0003,
		SendSmallPackageFromPcToTargetDevice = 0xDC1A,
		SendSmallPackageFromPcToTargetDeviceResponse = 0xDC1B,
		SendTotalQtyOfPackagesFromPcToTargetDevice = 0xDC16,
		SendTotalQtyOfPackagesFromPcToTargetDeviceResponse = 0xDC17,
		SequenceControl = 0x001A,
		SequenceControlResponse = 0x001B,
		SubnetBroadcastToAllDevices = 0x0288,
		WhichModulesAreProgrammedIntoTheHardwareState = 0x0286,
		WhichModulesAreProgrammedIntoTheHardwareStateResponse = 0x0287,
		WriteChannelRemark = 0xF010,
		WriteChannelRemarkResponse = 0xF011,
		WriteDeviceRemark = 0x0010,
		WriteDeviceRemarkResponse = 0x0011,
		WriteLimitOfEveryChannel = 0xF018,
		WriteLimitOfEveryChannelResponse = 0xF019,
		WriteRemarkOfOneZone = 0xF00C,
		WriteRemarkOfOneZoneResponse = 0xF00D,
		WriteRemarkOfSpecifiedSceneOfSpecifiedZone = 0xF026,
		WriteRemarkOfSpecifiedSceneOfSpecifiedZoneResponse = 0xF027,
		WriteTypeOfZoneWhenPowerOn = 0xF053,
		WriteTypeOfZoneWhenPowerOnResponse = 0xF054,

		ReadTemperatureOutside = 0x018C,
		ReadTemperatureOutsideResponse = 0x018D,
		ModifyTemperatureOutside = 0x018E,
		ModifyTemperatureOutsideResponse = 0x018F,
		ReadTemperaturRangeOfSpecifiedLogicBlock = 0xD999,
		ReadTemperaturRangeOfSpecifiedLogicBlockResponse = 0xD99A,
		ModifyTemperaturRangeOfSpecifiedLogicBlock = 0xD997,
		ModifyTemperaturRangeOfSpecifiedLogicBlockResponse = 0xD998,
		ReadCompensationOfBrightness = 0xDA00,
		ReadCompensationOfBrightnessResponse = 0xDA01,
		ModifyCompensationOfBrightness = 0xDA02,
		ModifyCompensationOfBrightnessResponse = 0xDA03,
		ReadSensorsStatus = 0xDB00,
		ReadSensorsStatusResponse = 0xDB01,
		ReadPirSensitivity = 0xD828,
		ReadPirSensitivityResponse = 0xD829,
		ModifydPirSensitivity = 0xD826,
		ModifyPirSensitivityResponse = 0xD827,
		ReadDelayTimeOfPir = 0xD818,
		ReadDelayTimeOfPirResponse = 0xD819,
		ModifyDelayTimeOfPir = 0xD80C,
		ModifyDelayTimeOfPirResponse = 0xD80D,
		ReadCurrentBrightness = 0xD992,
		ReadCurrentBrightnessResponse = 0xD993,
		EnableEditingLogicPage = 0xDB30,
		EnableEditingLogicPageResponse = 0xDB31,
		EnableReadLogicPage = 0xDB32,
		EnableReadLogicPageResponse = 0xDB33,
		WriteRemarkOfLogic = 0xD988,
		WriteRemarkOfLogicResponse = 0xD989,
		ReadRemarkOfLogic = 0xD986,
		ReadRemarkOfLogicResponse = 0xD987,
		UniversalSwitchControl = 0xE01C,
		UniversalSwitchControlResponse = 0xE01D,
		BroadcastSystemDateTime = 0xDA44,

		ReadAcCurrentStatus = 0xE0EC,
		ReadAcCurrentStatusResponse = 0xE0ED,

		ReadFloorHeatingStatus = 0x1944,
		ReadFloorHeatingStatusResponse = 0x1945,

		ReadStatusPir = 0x1645,
		ReadStatusPirResponse = 0x1646,

		BroadcastTemperature = 0xE3E5,

		ReadTemperature = 0xE3E7,
		ReadTemperatureResponse = 0xE3E8,
		
		BroadcastSensorsStatus = 0x1647,

		ReadFloorHeatingSettings = 0x1940,
		ReadFloorHeatingSettingsResponse = 0x1941,

		ControlFloorHeatingStatus = 0x1946,
		ControlFloorHeatingStatusResponse = 0x1947,

		BroadcastStatusOfSequence = 0xF036,





		XX_QUERY_DLP_FROM_SETUP_TOOL_1 = 0xE0E4,
		XX_RESPONSE_QUERY_DLP_FROM_SETUP_TOOL_1 = 0xE0E5,
		XX_QUERY_12in1_FROM_SETUP_TOOL_3 = 0xDB3E,
		XX_RESPONSE_QUERY_12in1_FROM_SETUP_TOOL_3 = 0xDB3F,
		XX_QUERY_12in1_FROM_SETUP_TOOL_4 = 0x1666,
		XX_RESPONSE_QUERY_12in1_FROM_SETUP_TOOL_4 = 0x1667,
		XX_QUERY_12in1_FROM_SETUP_TOOL_6 = 0x165E,
		XX_RESPONSE_QUERY_12in1_FROM_SETUP_TOOL_6 = 0x165F,
		XX_QUERY_12in1_FROM_SETUP_TOOL_7 = 0x1641,
		XX_RESPONSE_QUERY_12in1_FROM_SETUP_TOOL_7 = 0x1642,
		XX_QUERY_12in1_FROM_SETUP_TOOL_8 = 0x166E,
		XX_RESPONSE_QUERY_12in1_FROM_SETUP_TOOL_8 = 0x166F,
		XX_QUERY_12in1_FROM_SETUP_TOOL_9 = 0x16A9,
		XX_RESPONSE_QUERY_12in1_FROM_SETUP_TOOL_9 = 0x16AA
	}
}
